version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=identityserver_management_Identity
      - identityserver_management_DB=identityserver_management_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
